FROM --platform=linux/arm64 registry.access.redhat.com/ubi8/ubi-minimal:latest AS go-builder

ENV PATH="$PATH:/usr/local/go/bin" \
    GOPATH=/go \
    GO_VERSION=1.24.4
ENV GO_SHA256="7ac7b396a691e588c5fb57687759e6c4db84a2a3bbebb0765f4b38e5b1c5b00e go${GO_VERSION}.linux-arm64.tar.gz"

RUN microdnf install -y git tar gzip ca-certificates && \
    microdnf clean all && \
    curl -L --fail --show-error --silent "https://go.dev/dl/go${GO_VERSION}.linux-arm64.tar.gz" -o "go${GO_VERSION}.linux-arm64.tar.gz" && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf "go${GO_VERSION}.linux-arm64.tar.gz" && \
    mkdir -p "${GOPATH}" && \
    go version

FROM --platform=linux/arm64 go-builder AS elector-builder

WORKDIR /go/src/project
COPY . .

RUN cd /go/src/project && \
    go mod tidy && \
    export ARCH=arm64 && \
    CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} GO111MODULE=on go build -a -installsuffix cgo -ldflags '-w' -o leader-elector_${ARCH} ./election/example/main.go && \
    mkdir -p /usr/bin/linux/${ARCH} && \
    chmod u+x leader-elector_* && \
    cp leader-elector_${ARCH} /usr/bin/linux/${ARCH}/leader-elector

FROM --platform=linux/arm64 go-builder AS hostname-builder

WORKDIR /go/src/project
COPY hostname.go .

RUN export ARCH=arm64 && \
    CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} GO111MODULE=off go build -a -installsuffix cgo -ldflags '-w' -o hostname_${ARCH} hostname.go && \
    mkdir -p /usr/bin/linux/${ARCH} && \
    chmod u+x hostname_* && \
    cp hostname_${ARCH} /usr/bin/linux/${ARCH}/hostname

# 최종 이미지
FROM --platform=linux/arm64 registry.access.redhat.com/ubi8/ubi-minimal:latest

MAINTAINER Instana Engineering <support@instana.com>

RUN microdnf install -y ca-certificates bash net-tools && \
    microdnf clean all

COPY --from=elector-builder /usr/bin/linux/arm64/leader-elector /app/server
COPY --from=hostname-builder /usr/bin/linux/arm64/hostname /app/hostname
COPY election/run.sh /app/run.sh

# run.sh 실행 권한 부여
RUN chmod +x /app/run.sh

# 디버깅용 로그 레벨 설정
ENV KLOG_V=4

USER 1001
ENTRYPOINT ["/app/run.sh"]